// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqbr46j34PbbNFc--X-IiIzLqUCsTmh2U',
    appId: '1:311076965491:web:dbfe118ef94ba10ae6ee06',
    messagingSenderId: '311076965491',
    projectId: 'fir-test-55b10',
    authDomain: 'fir-test-55b10.firebaseapp.com',
    storageBucket: 'fir-test-55b10.firebasestorage.app',
    measurementId: 'G-7GZLLFCFZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Fd0_Z0MlABLhI22PMjhVNTiIYJdnRcQ',
    appId: '1:311076965491:android:11d2247a56f71a39e6ee06',
    messagingSenderId: '311076965491',
    projectId: 'fir-test-55b10',
    storageBucket: 'fir-test-55b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcvHCgRwKtc7APws-aEYAcg2POJt_1RZE',
    appId: '1:311076965491:ios:8b66548a5dbf30b3e6ee06',
    messagingSenderId: '311076965491',
    projectId: 'fir-test-55b10',
    storageBucket: 'fir-test-55b10.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqbr46j34PbbNFc--X-IiIzLqUCsTmh2U',
    appId: '1:311076965491:web:a985654fab8b24a6e6ee06',
    messagingSenderId: '311076965491',
    projectId: 'fir-test-55b10',
    authDomain: 'fir-test-55b10.firebaseapp.com',
    storageBucket: 'fir-test-55b10.firebasestorage.app',
    measurementId: 'G-H7BVKNQ5L2',
  );
}
